[package]
name = "keccak-script"
version = { workspace = true }
edition = { workspace = true }
default-run = "keccak-script"
publish = false

[dependencies]
itertools = "0.12.1"
sp1-sdk = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-stark = { workspace = true }
sp1-core-machine = { workspace = true }
sha2 = "0.10.8"
clap = { version = "4.5.13", features = ["derive"] }

[build-dependencies]
sp1-build = { workspace = true }

[[bin]]
name = "groth16_bn254"
path = "bin/groth16_bn254.rs"

[[bin]]
name = "compressed"
path = "bin/compressed.rs"

[[bin]]
name = "execute"
path = "bin/execute.rs"

[[bin]]
name = "keccak-script"
path = "src/main.rs"

[features]
cuda = ["sp1-sdk/cuda"]
